apiVersion: v1
kind: Service
metadata:
  name: bootcamp2-windows-service
  namespace: bootcamp2-app
  labels:
    app: bootcamp2-windows-app
spec:
  selector:
    app: bootcamp2-windows-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80