apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      foo: web
  template:
    metadata:
      labels:
        foo: web
    spec:
      containers:
        - name: foo
          image: public.ecr.aws/o2x5s7z9/bootcamp2a
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  namespace: default
spec:
  type: LoadBalancer
  selector:
    foo: web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bar
spec:
  backend:
    serviceName: bar
    servicePort: 5000
