apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      foo: web
  template:
    metadata:
      labels:
        foo: web
    spec:
      containers:
        - name: foo
          image: bootcamp2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: bar
  namespace: default
spec:
  type: NodePort
  selector:
    foo: web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
